In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df=pd.read_excel("Candidate Application Tracker.xlsx")
print(df)

    Unnamed: 0      Unnamed: 1         Unnamed: 2                  Unnamed: 3  \
0       S. No.  Candidate Name     Counselor Name  Block Amount Received Date
1            1          Vikash  Shailendra Singh                        45152
2            2         Hariraj  Shailendra Singh                        45188
3            3        Thippesh  Shailendra Singh                        45190
4            4         Chintan  Shailendra Singh                        45202
..         ...             ...                ...                         ...
312        312          Alladi   Rishabh Tripathi                       45397
313        313        Shrishti   Rishabh Tripathi                       45397
314        314         purnima   Rishabh Tripathi                       45397
315        315           ashok    Diptikanta Jena                       45397
316        NaN             NaN                NaN                         NaN

           Unnamed: 4          Unnamed: 5  \
0       Univ. Pitched             Lead Id
1             Rutgers                 NaN
2    Fairfield/DePaul                 NaN
3             Rutgers                 NaN
4              DePaul                 NaN
..                ...                 ...
312               NaN                 NaN
313               NaN  l:1347108042669193
314               NaN   l:430457079653387
315               NaN  l:1441157749822520
316               NaN                 NaN

                                            Unnamed: 6  \
0                       Candidate Preferred College #1
1                              Rutgers Business School
2         DePaul Kellstadt Graduate School of Business
3                              Rutgers Business School
4         DePaul Kellstadt Graduate School of Business
..                                                 ...
312  West Texas A&M University, Paul and Virginia E...
313  University at Buffalo (SUNY), School of Manage...
314                                                NaN
315                                                NaN
316                                                NaN

                                       Unnamed: 7        Unnamed: 8  \
0                  Candidate Preferred College #2  10th Percentage
1                                             NaN               NaN
2                                             NaN               NaN
3                                             NaN               NaN
4                                             NaN               NaN
..                                            ...               ...
312  DePaul Kellstadt Graduate School of Business              81.7
313                       Rutgers Business School              91.2
314                                           NaN               NaN
315                                           NaN               NaN
316                                           NaN               NaN

           Unnamed: 9  ...                  Unnamed: 133 Unnamed: 134  \
0    12th Percentange  ...  Offer Letter Submission Date
1                 NaN  ...                           NaN          NaN
2                 NaN  ...                           NaN          NaN
3                 NaN  ...                           NaN          NaN
4                 NaN  ...                           NaN          NaN
..                ...  ...                           ...          ...
312              90.6  ...                           NaN          NaN
313             67.33  ...                           NaN          NaN
314               NaN  ...                           NaN          NaN
315               NaN  ...                           NaN          NaN
316               NaN  ...                           NaN          NaN

                 i20 Stage                Unnamed: 136     Unnamed: 137  \
0    Financials Submission  Financials Submission Date  i20 Provisioned
1                     True                         NaN         Received
2                    False                         NaN              NaN
3                     True                  20/02/2024         Received
4                     True                         NaN         Received
..                     ...                         ...              ...
312                    NaN                         NaN              NaN
313                    NaN                         NaN              NaN
314                    NaN                         NaN              NaN
315                    NaN                         NaN              NaN
316                    NaN                         NaN              NaN

             Unnamed: 138                      Unnamed: 139  \
0    i20 Provisioned Date                           Remarks
1              14/03/2024                               NaN
2                     NaN     On Hold due to CX In Hospital
3              20/02/2024                               NaN
4              28/03/2024  was On Hold due to family issues
..                    ...                               ...
312                   NaN                               NaN
313                   NaN                               NaN
314                   NaN                               NaN
315                   NaN                               NaN
316                   NaN                               NaN

             Unnamed: 140 Unnamed: 141 Unnamed: 142
0                 Status    SOP Status
1              Defer Fall          NaN          NaN
2              Defer Fall          NaN          NaN
3              Defer Fall          NaN          NaN
4    Defer Fall (Dropped)          NaN          NaN
..                    ...          ...          ...
312           Spring 2025          NaN          NaN
313                  Fall          NaN          NaN
314           Spring 2025          NaN          NaN
315           Spring 2025          NaN          NaN
316                   NaN          NaN          NaN

[317 rows x 143 columns]

In [3]:
df.iloc[0]
df.head(1)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 133,Unnamed: 134,i20 Stage,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142
0,S. No.,Candidate Name,Counselor Name,Block Amount Received Date,Univ. Pitched,Lead Id,Candidate Preferred College #1,Candidate Preferred College #2,10th Percentage,12th Percentange,...,Offer Letter Submission Date,,Financials Submission,Financials Submission Date,i20 Provisioned,i20 Provisioned Date,Remarks,Status,SOP Status,

In [4]:

df = df.loc[:, df.iloc[0].notnull()]

df.reset_index(drop=True, inplace=True)

print(df)

    Unnamed: 0      Unnamed: 1         Unnamed: 2                  Unnamed: 3  \
0       S. No.  Candidate Name     Counselor Name  Block Amount Received Date
1            1          Vikash  Shailendra Singh                        45152
2            2         Hariraj  Shailendra Singh                        45188
3            3        Thippesh  Shailendra Singh                        45190
4            4         Chintan  Shailendra Singh                        45202
..         ...             ...                ...                         ...
312        312          Alladi   Rishabh Tripathi                       45397
313        313        Shrishti   Rishabh Tripathi                       45397
314        314         purnima   Rishabh Tripathi                       45397
315        315           ashok    Diptikanta Jena                       45397
316        NaN             NaN                NaN                         NaN

           Unnamed: 4          Unnamed: 5  \
0       Univ. Pitched             Lead Id
1             Rutgers                 NaN
2    Fairfield/DePaul                 NaN
3             Rutgers                 NaN
4              DePaul                 NaN
..                ...                 ...
312               NaN                 NaN
313               NaN  l:1347108042669193
314               NaN   l:430457079653387
315               NaN  l:1441157749822520
316               NaN                 NaN

                                            Unnamed: 6  \
0                       Candidate Preferred College #1
1                              Rutgers Business School
2         DePaul Kellstadt Graduate School of Business
3                              Rutgers Business School
4         DePaul Kellstadt Graduate School of Business
..                                                 ...
312  West Texas A&M University, Paul and Virginia E...
313  University at Buffalo (SUNY), School of Manage...
314                                                NaN
315                                                NaN
316                                                NaN

                                       Unnamed: 7        Unnamed: 8  \
0                  Candidate Preferred College #2  10th Percentage
1                                             NaN               NaN
2                                             NaN               NaN
3                                             NaN               NaN
4                                             NaN               NaN
..                                            ...               ...
312  DePaul Kellstadt Graduate School of Business              81.7
313                       Rutgers Business School              91.2
314                                           NaN               NaN
315                                           NaN               NaN
316                                           NaN               NaN

           Unnamed: 9  ...                  Unnamed: 133 Unnamed: 134  \
0    12th Percentange  ...  Offer Letter Submission Date
1                 NaN  ...                           NaN          NaN
2                 NaN  ...                           NaN          NaN
3                 NaN  ...                           NaN          NaN
4                 NaN  ...                           NaN          NaN
..                ...  ...                           ...          ...
312              90.6  ...                           NaN          NaN
313             67.33  ...                           NaN          NaN
314               NaN  ...                           NaN          NaN
315               NaN  ...                           NaN          NaN
316               NaN  ...                           NaN          NaN

                 i20 Stage                Unnamed: 136     Unnamed: 137  \
0    Financials Submission  Financials Submission Date  i20 Provisioned
1                     True                         NaN         Received
2                    False                         NaN              NaN
3                     True                  20/02/2024         Received
4                     True                         NaN         Received
..                     ...                         ...              ...
312                    NaN                         NaN              NaN
313                    NaN                         NaN              NaN
314                    NaN                         NaN              NaN
315                    NaN                         NaN              NaN
316                    NaN                         NaN              NaN

             Unnamed: 138                      Unnamed: 139  \
0    i20 Provisioned Date                           Remarks
1              14/03/2024                               NaN
2                     NaN     On Hold due to CX In Hospital
3              20/02/2024                               NaN
4              28/03/2024  was On Hold due to family issues
..                    ...                               ...
312                   NaN                               NaN
313                   NaN                               NaN
314                   NaN                               NaN
315                   NaN                               NaN
316                   NaN                               NaN

             Unnamed: 140 Unnamed: 141 Unnamed: 142
0                 Status    SOP Status
1              Defer Fall          NaN          NaN
2              Defer Fall          NaN          NaN
3              Defer Fall          NaN          NaN
4    Defer Fall (Dropped)          NaN          NaN
..                    ...          ...          ...
312           Spring 2025          NaN          NaN
313                  Fall          NaN          NaN
314           Spring 2025          NaN          NaN
315           Spring 2025          NaN          NaN
316                   NaN          NaN          NaN

[317 rows x 143 columns]

In [5]:


print(df)

    Unnamed: 0      Unnamed: 1         Unnamed: 2                  Unnamed: 3  \
0       S. No.  Candidate Name     Counselor Name  Block Amount Received Date
1            1          Vikash  Shailendra Singh                        45152
2            2         Hariraj  Shailendra Singh                        45188
3            3        Thippesh  Shailendra Singh                        45190
4            4         Chintan  Shailendra Singh                        45202
..         ...             ...                ...                         ...
312        312          Alladi   Rishabh Tripathi                       45397
313        313        Shrishti   Rishabh Tripathi                       45397
314        314         purnima   Rishabh Tripathi                       45397
315        315           ashok    Diptikanta Jena                       45397
316        NaN             NaN                NaN                         NaN

           Unnamed: 4          Unnamed: 5  \
0       Univ. Pitched             Lead Id
1             Rutgers                 NaN
2    Fairfield/DePaul                 NaN
3             Rutgers                 NaN
4              DePaul                 NaN
..                ...                 ...
312               NaN                 NaN
313               NaN  l:1347108042669193
314               NaN   l:430457079653387
315               NaN  l:1441157749822520
316               NaN                 NaN

                                            Unnamed: 6  \
0                       Candidate Preferred College #1
1                              Rutgers Business School
2         DePaul Kellstadt Graduate School of Business
3                              Rutgers Business School
4         DePaul Kellstadt Graduate School of Business
..                                                 ...
312  West Texas A&M University, Paul and Virginia E...
313  University at Buffalo (SUNY), School of Manage...
314                                                NaN
315                                                NaN
316                                                NaN

                                       Unnamed: 7        Unnamed: 8  \
0                  Candidate Preferred College #2  10th Percentage
1                                             NaN               NaN
2                                             NaN               NaN
3                                             NaN               NaN
4                                             NaN               NaN
..                                            ...               ...
312  DePaul Kellstadt Graduate School of Business              81.7
313                       Rutgers Business School              91.2
314                                           NaN               NaN
315                                           NaN               NaN
316                                           NaN               NaN

           Unnamed: 9  ...                  Unnamed: 133 Unnamed: 134  \
0    12th Percentange  ...  Offer Letter Submission Date
1                 NaN  ...                           NaN          NaN
2                 NaN  ...                           NaN          NaN
3                 NaN  ...                           NaN          NaN
4                 NaN  ...                           NaN          NaN
..                ...  ...                           ...          ...
312              90.6  ...                           NaN          NaN
313             67.33  ...                           NaN          NaN
314               NaN  ...                           NaN          NaN
315               NaN  ...                           NaN          NaN
316               NaN  ...                           NaN          NaN

                 i20 Stage                Unnamed: 136     Unnamed: 137  \
0    Financials Submission  Financials Submission Date  i20 Provisioned
1                     True                         NaN         Received
2                    False                         NaN              NaN
3                     True                  20/02/2024         Received
4                     True                         NaN         Received
..                     ...                         ...              ...
312                    NaN                         NaN              NaN
313                    NaN                         NaN              NaN
314                    NaN                         NaN              NaN
315                    NaN                         NaN              NaN
316                    NaN                         NaN              NaN

             Unnamed: 138                      Unnamed: 139  \
0    i20 Provisioned Date                           Remarks
1              14/03/2024                               NaN
2                     NaN     On Hold due to CX In Hospital
3              20/02/2024                               NaN
4              28/03/2024  was On Hold due to family issues
..                    ...                               ...
312                   NaN                               NaN
313                   NaN                               NaN
314                   NaN                               NaN
315                   NaN                               NaN
316                   NaN                               NaN

             Unnamed: 140 Unnamed: 141 Unnamed: 142
0                 Status    SOP Status
1              Defer Fall          NaN          NaN
2              Defer Fall          NaN          NaN
3              Defer Fall          NaN          NaN
4    Defer Fall (Dropped)          NaN          NaN
..                    ...          ...          ...
312           Spring 2025          NaN          NaN
313                  Fall          NaN          NaN
314           Spring 2025          NaN          NaN
315           Spring 2025          NaN          NaN
316                   NaN          NaN          NaN

[317 rows x 143 columns]

In [6]:
import pandas as pd


df.columns = df.iloc[0]

df = df[1:]

df.reset_index(drop=True, inplace=True)

print(df)

0   S. No. Candidate Name     Counselor Name Block Amount Received Date  \
0        1         Vikash  Shailendra Singh                       45152
1        2        Hariraj  Shailendra Singh                       45188
2        3       Thippesh  Shailendra Singh                       45190
3        4        Chintan  Shailendra Singh                       45202
4        5          Sagar  Shailendra Singh                       45181
..     ...            ...                ...                        ...
311    312         Alladi   Rishabh Tripathi                      45397
312    313       Shrishti   Rishabh Tripathi                      45397
313    314        purnima   Rishabh Tripathi                      45397
314    315          ashok    Diptikanta Jena                      45397
315    NaN            NaN                NaN                        NaN

0       Univ. Pitched             Lead Id  \
0             Rutgers                 NaN
1    Fairfield/DePaul                 NaN
2             Rutgers                 NaN
3              DePaul                 NaN
4             Rutgers                 NaN
..                ...                 ...
311               NaN                 NaN
312               NaN  l:1347108042669193
313               NaN   l:430457079653387
314               NaN  l:1441157749822520
315               NaN                 NaN

0                       Candidate Preferred College #1  \
0                              Rutgers Business School
1         DePaul Kellstadt Graduate School of Business
2                              Rutgers Business School
3         DePaul Kellstadt Graduate School of Business
4                              Rutgers Business School
..                                                 ...
311  West Texas A&M University, Paul and Virginia E...
312  University at Buffalo (SUNY), School of Manage...
313                                                NaN
314                                                NaN
315                                                NaN

0                  Candidate Preferred College #2 10th Percentage   \
0                                             NaN              NaN
1                                             NaN              NaN
2                                             NaN              NaN
3                                             NaN              NaN
4                                             NaN              NaN
..                                            ...              ...
311  DePaul Kellstadt Graduate School of Business             81.7
312                       Rutgers Business School             91.2
313                                           NaN              NaN
314                                           NaN              NaN
315                                           NaN              NaN

0   12th Percentange  ... Offer Letter Submission Date       \
0                NaN  ...                          NaN  NaN
1                NaN  ...                          NaN  NaN
2                NaN  ...                          NaN  NaN
3                NaN  ...                          NaN  NaN
4                NaN  ...                        45224  NaN
..               ...  ...                          ...  ...
311             90.6  ...                          NaN  NaN
312            67.33  ...                          NaN  NaN
313              NaN  ...                          NaN  NaN
314              NaN  ...                          NaN  NaN
315              NaN  ...                          NaN  NaN

0   Financials Submission Financials Submission Date i20 Provisioned  \
0                    True                        NaN        Received
1                   False                        NaN             NaN
2                    True                 20/02/2024        Received
3                    True                        NaN        Received
4                    True                 18/02/2024        Received
..                    ...                        ...             ...
311                   NaN                        NaN             NaN
312                   NaN                        NaN             NaN
313                   NaN                        NaN             NaN
314                   NaN                        NaN             NaN
315                   NaN                        NaN             NaN

0   i20 Provisioned Date                           Remarks  \
0             14/03/2024                               NaN
1                    NaN     On Hold due to CX In Hospital
2             20/02/2024                               NaN
3             28/03/2024  was On Hold due to family issues
4             21/02/2024                               NaN
..                   ...                               ...
311                  NaN                               NaN
312                  NaN                               NaN
313                  NaN                               NaN
314                  NaN                               NaN
315                  NaN                               NaN

0                 Status  SOP Status
0              Defer Fall        NaN  NaN
1              Defer Fall        NaN  NaN
2              Defer Fall        NaN  NaN
3    Defer Fall (Dropped)        NaN  NaN
4              Defer Fall        NaN  NaN
..                    ...        ...  ...
311           Spring 2025        NaN  NaN
312                  Fall        NaN  NaN
313           Spring 2025        NaN  NaN
314           Spring 2025        NaN  NaN
315                   NaN        NaN  NaN

[316 rows x 143 columns]

In [7]:

headers = df.columns.tolist()

print(headers)
df.to_csv("Candidate Application Tracker.csv",index=False)

['S. No.', 'Candidate Name', 'Counselor Name', 'Block Amount Received Date', 'Univ. Pitched', 'Lead Id', 'Candidate Preferred College #1', 'Candidate Preferred College #2', '10th Percentage ', '12th Percentange', 'UG - CGPA (out of 10) ', 'GPA (Out of 4)', 'PG - CGPA or %', 'Work Exp.', 'Highest Education', 'Designation - Company Name ', 'Candidate Application Status', 'Candidate Loan Status', 'Remarks - General', 'Reason for dropping', 'If dropped, mention stage of the application', ' ', 'KYC & Acad Documents Received', 'Tech Exam Scores', 'Coding Test Score', 'English Exam Scores', 'Exam Taking Date', 'English Interview Score (15)', 'Tech. interview Score (10)', ' ', 'Application Type', 'Intake Status', ' ', 'Choice of School #1', 'Choice of Program #1', 'Passport #1', 'Resume #1', 'Degree #1', 'Transcript #1', 'Application Fee #1', 'LOR #1', 'SOP #1', 'Pending Stage #1', 'Application Status #1', 'Application Initation Date #1', 'App Partially Submitted Date #1', 'Application Submission Date #1', 'Offer Letter #1', 'Offer Letter Provision Date #1', 'Deposit #1', 'Deposit Date Paid #1', ' ', 'Choice of School #2', 'Choice of Program #2', 'Application Fee #2', 'LOR #2', 'SOP #2', 'Pending Stage #2', 'Application Status #2', 'Application Initation Date #2', 'App Partially Submitted Date #2', 'Application Submission Date #2', 'Offer Letter #2', 'Offer Letter Provision Date #2', 'Deposit #2', 'Deposit Date Paid #2', ' ', 'Choice of School #3', 'Choice of Program #3', 'Application Fee #3', 'LOR #3', 'SOP #3', 'Pending Stage #3', 'Application Status #3', 'Application Initation Date #3', 'App Partially Submitted Date #3', 'Application Submission Date #3', 'Offer Letter #3', 'Offer Letter Provision Date #3', 'Deposit #3', 'Deposit Date Paid #3', 'Remarks #3 (If Rejected)', ' ', 'Choice of School #4', 'Choice of Program #4', 'Application Fee #4', 'LOR #4', 'SOP #4', 'Pending Stage #4', 'Application Status #4', 'Application Initation Date #4', 'App Partially Submitted Date #4', 'Application Submission Date #4', 'Offer Letter #4', 'Offer Letter Provision Date #4', 'Deposit #4', 'Deposit Date Paid #4', 'Remarks #4 (If Rejected)', ' ', 'Choice of School #5', 'Choice of Program #5', 'Application Fee #5', 'LOR #5', 'SOP #5', 'Pending Stage #5', 'Application Status #5', 'Application Initation Date #5', 'App Partially Submitted Date #5', 'Application Submission Date #5', 'Offer Letter #5', 'Offer Letter Provision Date #5', 'Deposit #5', 'Deposit Date Paid #5', 'Remarks #5 (If Rejected)', ' ', 'IIM / IIT  Status', ' Loan Status', 'Loan Partner I', 'Loan Partner II', 'Loan Application Submit Date', 'Existing Loan', 'CIBIL SCORE', 'No. of defaults', ' ', 'Aadhar Card', 'PAN Card', 'Passport', 'CV/Resume', 'CIBIL Score', 'Bank Statement (Savings - 6mo)', 'Affidavit Letter', 'Sponsorship Letter', 'Offer Letter', 'Offer Letter Submission Date', ' ', 'Financials Submission', 'Financials Submission Date', 'i20 Provisioned', 'i20 Provisioned Date', 'Remarks', 'Status ', 'SOP Status', ' ']